Docker Compose, chown data volume, gosu 1.7

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -7,9 +7,13 @@ function fail {
 
 [[ -z "$CONF_RPCPASSWORD" ]] && fail "Required environment variable CONF_RPCPASSWORD not set."
 
+if [[ -n "$NO_CHOWN" ]] ; then
+	chown -R bitcoin:bitcoin /bitcoin/data || fail "Cannot change ownership of '/bitcoin/data'."
+fi
+
 env | grep '^CONF_\w\+=' | cut -d= -f1 | while read EVAR ; do
 	CVAR=`echo "$EVAR" | cut -d_ -f2- | tr '[:upper:]' '[:lower:]'`
-	echo "${CVAR}=${!EVAR}" | tee -a /etc/bitcoin.conf
+	echo "${CVAR}=${!EVAR}" >> /etc/bitcoin.conf
 done
 
 exec gosu bitcoin /usr/bin/bitcoind -conf=/etc/bitcoin.conf
